piVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qdrant.fullname" . }}
  {{- if .Values.qdrant.serviceAccount.annotations }}
annotations:
  {{ toYaml .Values.serviceAccount.annotations | indent 4 }}
  {{- end }}
labels:
  {{- include "qdrant.labels" . | nindent 4 }}
