{{- if .Values.qdrant.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "qdrant.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
    {{- with .Values.qdrant.ingress.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.qdrant.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.qdrant.ingress.ingressClassName }}
  ingressClassName: {{ .Values.qdrant.ingress.ingressClassName }}
  {{- end }}
  {{- with .Values.qdrant.ingress.hosts }}
  rules:
    {{- range . }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | default "Prefix" | quote }}
            backend:
              service:
                name: {{ default .serviceName (include "qdrant.fullname" $) }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.qdrant.ingress.tls }}
  tls:
    {{- range .Values.qdrant.ingress.tls}}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName | quote }}
    {{- end }}
  {{- end }}
{{- end }}
