{{- if or .Values.qdrant.apiKey .Values.qdrant.readOnlyApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qdrant.fullname" . }}-apikey
data:
{{ include "qdrant.secret" . | indent 2}}
{{- end }}
