apiVersion: v1
kind: Service
metadata:
  name: {{ include "meetverse.fullname" . }}-fe
  labels:
    {{- include "meetverse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "meetverse.name" . }}-fe
    app.kubernetes.io/instance: {{ .Release.Name }}
