apiVersion: v1
kind: Service
metadata:
  name: {{ include "meetverse.fullname" . }}-fe
  labels:
    {{- include "meetverse.labels-fe" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "meetverse.selectorLabels-fe" . | nindent 4 }}
